ignore:
  - .git
  - .streamlit
  - venv
  - resources
  - .vscode
  - .gitignore
  - .gitattributes
refactor:
  python_version: '3.9'
  skip:
    - assign-if-exp
    - merge-nested-ifs
    - inline-immediately-returned-variable
    - list-literal
    - dict-literal
    - use-named-expression
